### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by savely-krasovsky** [Totktonada/vk_messages_backup#1]
Получил бэкап, но вылезло несколько ошибок, может я конечно, что-то напортачил, но всё-таки не  помешало бы проверить. https://cloud.krasovsky.me/s/DgRhEaX6KB9WnNv
За скрипт большое спасибо!

**Comment by Totktonada** [comment]
Спасибо за репорт!

Сейчас у меня не под рукой нужное окружение, чтобы попробовать воспроизвести проблему. Но она в любом случае может быть специфична для конкретного ответа сервера.

Можете зашарить ответ, на котором вылетает exception? Для этого можно поменять [строку 89](https://github.com/Totktonada/vk_messages_backup/blob/686745a3864722d7950a6cdf26cdb88b3dd5d94d/messages_backup.py#L89) на нечто в духе:

```
        try:
            general_response = r.json()
        except:
            with open('issue-1-url.txt', 'w') as f:
                f.write(r.url)
            with open('issue-1-dump.txt', 'wb') as f:
                f.write(r.content)
            raise
```

URL и дамп можно прикрепить сюда или прислать на почту (указана в профиле). Если не хочется зашаривать дамп полностью, то хватит первых нескольких байт.

Кстати, у вас сгенерировались только файлы `*.json`, но `*.txt` — нет? Если так, то можно попробовать после [строки 499](https://github.com/Totktonada/vk_messages_backup/blob/686745a3864722d7950a6cdf26cdb88b3dd5d94d/messages_backup.py#L499) попробовать вызвать `storage.dump(dict())`. По идее тогда создадутся `*.txt` с id вместо имен пользователей.

**Comment by Totktonada** [comment]
(Обновил комментарий, заменил 'w' на 'wb'.)

**Comment by savely-krasovsky** [comment]
Наверно придется создать пустой аккаунт. Потому что бэкап делался около полутора часа. И ошибки я увидел только в конце. Ещё не помешало бы логирование, конечно, а то мне казалось, то скрипт не работает вовсе и просто ушел в бесконечный loop.

**Comment by Totktonada** [comment]
Все перекачивать не должен, если json-файлы на месте. Ошибка произошла где-то в попытках получить имена пользователей, а скачивание сообщений прошло успешно.

Аккаунт создавать не стоит. Если проблема не специфична для вашей ситуации, то у меня она тоже воспроизведется. Если нет, то важен именно тот ответ, что вы получаете для своего аккаунта.

**Comment by savely-krasovsky** [comment]
Понял, тогда попробую протестировать.

Штука лично для меня востребованная, хочется хранить переписку на всякий случай, потому что в некоторых мобильный клиентах (типа Kate Mobile, к примеру) очень просто её удалить тупо случайно.

**Comment by savely-krasovsky** [comment]
Из-за новой ошибки файл получился пустой: https://cloud.krasovsky.me/s/bgNnKBe20XGQHcj
На питоне вообще не пишу, поэтому внести хоть какие-то правки не могу...

**Comment by Totktonada** [comment]
Ага, мой косяк, r.url надо было как строку, а не байты писать в файл (обновил тот комментарий снова). Хоть url узнаем.

**Comment by savely-krasovsky** [comment]
issue-1-dump.txt:

```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/0.3.33</center>
</body>
</html>
```

А вот issue-1-url.txt это огроменный URL-запрос по методу users.get().
Там очень много людей, но так или иначе, это люди, которых у меня НЕТ в друзья. Думаю это важно.

**Comment by Totktonada** [comment]
Скачивается информация о пользователях, которые есть в диалогах или являются участниками групповых чатов. Проблему понял — формируется слишком длинный GET-запрос, нужно переделать в POST или сделать итеративное получение информации. Поскольку второе все равно по-хорошему надо бы сделать, реализую его.

**Comment by Totktonada** [comment]
Сделал, но пока сильно не тестировал. Попробуйте. Если что-то не получится, то переоткройте этот issue.
