### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by vlad00777** [Totktonada/vk_messages_backup#6]
Hi. I have some troubles with your script (decode json error).
![cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/5796753/26210982/97e4e26c-3bf1-11e7-8c40-4e1882cdc310.png)

**Comment by Totktonada** [comment]
Can you please add line with `print('DEBUG: storage filename: ' + filepath)` after [line 420](https://github.com/Totktonada/vk_messages_backup/blob/11aee43736e7da387ba4033f6cf1150b097ffde2/vk_messages_backup.py#L420)? And give some information about the file content aroud line 1148? Is it really invalid JSON?

NB: I don’t tried the script nor w/ Python 3.6 nor w/ Windows.

**Comment by vlad00777** [comment]
In json file:
`    {
        "body": "text1",
        "date": 1445896736,
        "id": 194628,
        "out": 0,
        "read_state": 1,
        "title": "",
        "user_id": 25380353
    },
    {
        "body": "text",
        "date": 1445896756,
        "id": 194629,
        "out": 1,
        "read_state": 1,
        "title": "",
        "user_id": 25380353
    },
    {
        "body": `
This is the end of this file.

Maybe special characters in body of message?

**Comment by Totktonada** [comment]
Ugh. The file is broken. I guess, you need to remove entire `storage` directory to give correct logs at the next run. Removing the only file is not enough because the script doesn’t check for 'holes' in a message sequence and give 'hole' in the resulting chatlog in case that 'hole' presents in the `storage` cache.

Is that write failure reproduces from run to run? How often?

**Comment by vlad00777** [comment]
> Is that write failure reproduces from run to run? How often?

Yes. I am tried rerun "vk_messages_backup. pi" and get this error again.

**Comment by Totktonada** [comment]
We are about clean rerun after removing the `storage` directory, yep?

**Comment by vlad00777** [comment]
Yes

**Comment by Totktonada** [comment]
Not sure how I can help you w/o Windows box in hands-on availability. Maybe some bad magic with opening files in 'text' mode occured on Windows and it worth to try to replace 'w' and 'r' with 'wb' and 'rb' anywhere in open() calls. Maybe another Python distribution would solve this problem: mingw and cygwin offers Python packages as I know.

**Comment by Chiaki** [comment]
I think I have the same problem on Windows. Reason of this problem could be in python which compiled without UTF-8 support for Windows. And when the script tries to create a filename which contains UTF-8 characters we have such error.

**Comment by Totktonada** [comment]
@Chiaki But in the original problem the file was partially written. I guess, a problem with a filename encoding would be lead to an error at opening the file.

**Comment by Chiaki** [comment]
@Totktonada Yes of course. I was able to get some files on Windows (mostly which have a numberic filename) and even some content was inside. Unfortunately I didn't made a screen shoot, but it was a 99% same as on topic. But maybe this is a different error, I'm not sure.

**Comment by Totktonada** [comment]
What Python distribution you use? Maybe I will try to reproduce this sooner or later.

**Comment by Chiaki** [comment]
I'm using Python 3.5.1 on Win7 x64.
I've recreated error, you was right. Error with encoding are different from described above. Here the code of the encoding error:
```
2017-08-06 03:09:08,180 INFO [get_vk_messages] Downloading from offset 19200...
2017-08-06 03:09:08,599 INFO [get_vk_messages] Downloading from offset 19400...
2017-08-06 03:09:09,091 INFO Saving messages to storage...
Traceback (most recent call last):
  File "c:\sys\vkbackup\vk_messages_backup.py", line 628, in <module>
    main()
  File "c:\sys\vkbackup\vk_messages_backup.py", line 609, in main
    storage.save()
  File "c:\sys\vkbackup\vk_messages_backup.py", line 399, in save
    dialog.save(self.storage_dir)
  File "c:\sys\vkbackup\vk_messages_backup.py", line 334, in save
    print_json(data, file=f)
  File "c:\sys\vkbackup\vk_messages_backup.py", line 44, in print_json
    sort_keys=True)
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\json\__init__.py
", line 179, in dump
    fp.write(chunk)
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\encodings\cp1251
.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60f' in posit
ion 33: character maps to <undefined>
```

And the error which I thought the same as described above is:
```
2017-08-06 03:16:32,784 INFO Loading messages from storage...
Traceback (most recent call last):
  File "c:\sys\vkbackup\vk_messages_backup.py", line 628, in <module>
    main()
  File "c:\sys\vkbackup\vk_messages_backup.py", line 600, in main
    storage.load()
  File "c:\sys\vkbackup\vk_messages_backup.py", line 421, in load
    for raw_msg in json.load(f):
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\json\__init__.py
", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\json\__init__.py
", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\json\decoder.py"
, line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Users\Chiaki\AppData\Local\Programs\Python\Python35\lib\json\decoder.py"
, line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 553 column 17 (char 12093)
```

I got it when tried to run script without arguments for config, storage and chatlogs.

**Comment by Totktonada** [comment]
@Chiaki Thanks!

**Comment by Totktonada** [comment]
I've added a status report into README: a0241bb2a6df600a9a52347f210ee5ac43cb5d7b. I have no plans to fix/maintain the script.
