### ISSUE TITLE
VK removes out params from messages.get

### ISSUE THREAD

**Issue by Totktonada** [Totktonada/vk_messages_backup#7]
VK say they will remove `out` param from `messages.get` requests after a month. I asked they how to get incoming messages in the case.

**Comment by Win2R** [comment]
Из-за этого у меня не отрабатывает скрипт?
![kali](https://user-images.githubusercontent.com/3756207/34361984-0d353fa0-ea78-11e7-91c1-7bcf3a4ec451.png)

**Comment by Totktonada** [comment]
@Xamon Давно не запускал. Сейчас запустил. Машина новая, старых дампов нет, качает…

**Comment by Totktonada** [comment]
У меня не падает, но работает некорректно. Исходящих нет, входящие дублируются. Python 3.6.3.

Does not crash for me, but works incorrectly. There are no outgoing messages in logs, but incoming messages duplicates.

**Comment by Win2R** [comment]
Аналогично. Входящих по два сообщения, исходящих вообще нет. Видимо что-то "подкрутили" в самом ВК, потому что буквально пол года назад все работало нормально.

**Comment by ujifgc** [comment]
vk.messages.get does not get outgoing messages anymore
vk.messages.getHistory does get them though

**Comment by Totktonada** [comment]
I've added a status report into README: a0241bb2a6df600a9a52347f210ee5ac43cb5d7b. I have no plans to fix/maintain the script.
